Lamb_Ji_UI/Controllers/ActualiteAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lamb_Ji_DAL;

namespace Lamb_Ji_UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ActualiteAdminController : Controller
    {
        private CNGLUTTEDBEntities db = new CNGLUTTEDBEntities();

        // GET: ActualiteAdmin
        public ActionResult Index()
        {
            return View(db.Actualites.ToList());
        }

        // GET: ActualiteAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actualite actualite = db.Actualites.Find(id);
            if (actualite == null)
            {
                return HttpNotFound();
            }
            return View(actualite);
        }

        // GET: ActualiteAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ActualiteAdmin/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "actuID,actuNom,actuTitre,actuDate,actuTexte,actuImgUrl")] Actualite actualite, HttpPostedFileBase ImageUpload)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (ImageUpload != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(ImageUpload.FileName);
                        string extension = Path.GetExtension(ImageUpload.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
                        actualite.actuImgUrl = fileName;
                        ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Image-Actu"), fileName));
                    }
                    actualite.actuDate = DateTime.Now;
                    db.Actualites.Add(actualite);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    throw;
                }
               
            }

            return View(actualite);
        }

        // GET: ActualiteAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actualite actualite = db.Actualites.Find(id);
            if (actualite == null)
            {
                return RedirectToAction("Index");
            }
            return View(actualite);
        }

        // POST: ActualiteAdmin/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "actuID,actuNom,actuTitre,actuDate,actuTexte,actuImgUrl")] Actualite actualite, HttpPostedFileBase ImageUpload)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (ImageUpload != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(ImageUpload.FileName);
                        string extension = Path.GetExtension(ImageUpload.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
                        actualite.actuImgUrl = fileName;
                        ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Image-Actu"), fileName));
                    }
                    actualite.actuDate = DateTime.Now;
                    db.Entry(actualite).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    return RedirectToAction("Index", "Error");
                }
               
            }
            return View(actualite);
        }

        // GET: ActualiteAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }
            Actualite actualite = db.Actualites.Find(id);
            if (actualite == null)
            {
                return HttpNotFound();
            }
            return View(actualite);
        }

        // POST: ActualiteAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Actualite actualite = db.Actualites.Find(id);
            db.Actualites.Remove(actualite);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lamb_Ji_UI/Views/ActualiteAdmin/Create.cshtml
@model Lamb_Ji_DAL.Actualite

@{
    ViewBag.Title = "Créer une nouvelle actualité";
}
<style>
    #myCarousel {
        display: none;
    }
</style>

<h2>Création d'une nouvelle actualité</h2>

@using (Html.BeginForm("Create", "ActualiteAdmin", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPost2(this);" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="form-horizontal">
            <h4>Nouvelle Actualite</h4>
            <hr />
            <div class="col-md-6">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.actuNom, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.actuNom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.actuNom, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.actuTitre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.actuTitre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.actuTitre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.actuTexte, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.actuTexte, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.actuTexte, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.actuImgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img src="~/Images/Image-Lutteur/default.png" style="margin:10px" height="250" width="200" id="imagePreview" />
                        <input id="ImageUpload" name="ImageUpload" class="form-control" type="file" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))" />
                    </div>
                </div>
            </div>
        </div>


    </div>
}

<div>
    @Html.ActionLink("Retourner à la Liste", "Index", null, new { @class = "btn btn-default btn-lg" })
</div>


@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>



        function ShowImagePreview(imageUploader, previewImage) {
            if (imageUploader.files && imageUploader.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(previewImage).attr('src', e.target.result);
                }
                reader.readAsDataURL(imageUploader.files[0]);
            }
        }


        function jQueryAjaxPost(form) {
            $.validator.unobtrusive.parse($('#SubmitForm'));
            if ($('#SubmitForm').valid()) {

                var ajaxConfig = {
                    type: 'POST',
                    url: form.action,
                    data: new FormData(form),
                    success: function () {
                        //$('#chargement').show();

                        //$('#chargement').hide();

                        toastr.info("Actuaité ajouté avec succés!!!....");

                    }
                }
                if ($(form).attr('enctype') == "multipart/form-data") {
                    ajaxConfig["contentType"] = false;
                    ajaxConfig["processData"] = false;
                }
                $.ajax(ajaxConfig);

            }
            return false;
        }

    </script>

}

Lamb_Ji_UI/Views/ActualiteAdmin/Delete.cshtml
@model Lamb_Ji_DAL.Actualite

@{
    ViewBag.Title = "Delete";
}
<style>
    #myCarousel {
        display: none;
    }
</style>
<h2>Supprimer une Actualité</h2>

<h3>Etes-vous sur de vouloir supprimer cet Actu?</h3>
<div>
    <h4>@Model.actuTitre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.actuTitre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actuTitre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.actuTexte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.actuTexte)
        </dd>



    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-danger" /> |
            @Html.ActionLink("Retourner à la Liste", "Index", null, new { @class = "btn btn-default btn-lg" })
        </div>
    }
</div>

Lamb_Ji_UI/Views/ActualiteAdmin/Edit.cshtml
@model Lamb_Ji_DAL.Actualite

@{
    ViewBag.Title = "Edit";
}
<style>
    #myCarousel {
        display: none;
    }
</style>
<h2>Editer une Actualité</h2>

@using (Html.BeginForm("Edit", "ActualiteAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Model.actuTitre</h4>
        <hr />
        <div class="col-md-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.actuID)
            <div class="form-group">
                @Html.LabelFor(model => model.actuNom, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.actuNom, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.actuNom, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.actuTitre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.actuTitre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.actuTitre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.actuTexte, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.actuTexte, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.actuTexte, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.actuImgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.actuImgUrl, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.actuImgUrl, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.actuImgUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="~/Images/Image-Actu/@Url.Content(Model.actuImgUrl)" style="margin:10px" height="250" width="200" id="imagePreview" />
                    <input id="ImageUpload" name="ImageUpload" class="form-control" type="file" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à la Liste", "Index", null, new { @class = "btn btn-default btn-lg" })
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>



        function ShowImagePreview(imageUploader, previewImage) {
            if (imageUploader.files && imageUploader.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(previewImage).attr('src', e.target.result);
                }
                reader.readAsDataURL(imageUploader.files[0]);
            }
        }

    </script>

}

Lamb_Ji_UI/Views/ActualiteAdmin/Index.cshtml
@model IEnumerable<Lamb_Ji_DAL.Actualite>

@{
    ViewBag.Title = "Index";
}
<style>
    #myCarousel {
        display: none;
    }
</style>
<h2>Gestion des Actualités</h2>


<p>
    @Html.ActionLink("Nouvelle Actualité", "Create", null, new { @class = "btn btn-primary btn-lg" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.actuNom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.actuTitre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.actuTexte)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.actuDate)
        </th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.actuNom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.actuTitre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.actuTexte).ToString().Substring(0, 20)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.actuDate)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.actuID }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Supp", "Delete", new { id = item.actuID }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>