Lamb_Ji_UI/Controllers/AfficheController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lamb_Ji_DAL;

namespace Lamb_Ji_UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AfficheController : Controller
    {
        private CNGLUTTEDBEntities db = new CNGLUTTEDBEntities();

        // GET: Affiche
        public ActionResult Index()
        {
            var affiches = db.Affiches
                .Include(a => a.Lutteur)
                .Include(a => a.Lutteur1)
                .Include(a => a.Combat);
            return View(affiches.ToList());
        }

        // GET: Affiche/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Affiche affiche = db.Affiches.Find(id);
            if (affiche == null)
            {
                return HttpNotFound();
            }
            return View(affiche);
        }

        // GET: Affiche/Create
        public ActionResult Create()
        {
            ViewBag.AfficheID = new SelectList(db.AvisAffiches, "AvisAfficheID", "Auteur");
            ViewBag.Lutteur_A = new SelectList(db.Lutteurs, "LutteurID", "LutteurName");
            ViewBag.Lutteru_B = new SelectList(db.Lutteurs, "LutteurID", "LutteurName");
            ViewBag.CombatID = new SelectList(db.Combats, "CombatID", "Combat_Description");
            return View();
        }

        // POST: Affiche/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AfficheID,AfficheNom,CombatID,Lutteur_A,Lutteru_B,DateCombat,Vaincqueur,imageUrl")] Affiche affiche, HttpPostedFileBase ImageUpload)
        {
            if (ModelState.IsValid)
            {
                ViewBag.AfficheID = new SelectList(db.AvisAffiches, "AvisAfficheID", "Auteur", affiche.AfficheID);
                ViewBag.Lutteur_A = new SelectList(db.Lutteurs, "LutteurID", "LutteurName", affiche.Lutteur_A);
                ViewBag.Lutteru_B = new SelectList(db.Lutteurs, "LutteurID", "LutteurName", affiche.Lutteru_B);
                ViewBag.CombatID = new SelectList(db.Combats, "CombatID", "Combat_Description", affiche.CombatID);

                ViewBag.result = "";

                Affiche verifLut_date = db.Affiches.Where(x => x.DateCombat == affiche.DateCombat 
                && (((x.Lutteur_A == affiche.Lutteur_A) || (x.Lutteur_A == affiche.Lutteru_B))
                || ((x.Lutteru_B == affiche.Lutteur_A) || (x.Lutteru_B == affiche.Lutteru_B))
                )).FirstOrDefault();

                try
                {
                   
                    if (ImageUpload != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(ImageUpload.FileName);
                        string extension = Path.GetExtension(ImageUpload.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
                        affiche.imageUrl = fileName;
                        ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Image-Affiche"), fileName));
                    }
                    if (affiche.Lutteur_A == affiche.Lutteru_B)
                    {
                        ViewBag.result = "Vous ne pouvez pas choisir le meme lutteur deux fois dans le meme combat";
                        return View(affiche);
                    }
                    if (verifLut_date != null)
                    {
                        ViewBag.result = "Un des deux lutteurs que vous avez choisit à déja un combat à cette date ";

                        return View(affiche);
                    }
                  

                    db.Affiches.Add(affiche);
                    db.SaveChanges();



                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    return RedirectToAction("Index", "Error");
                }
               
            }

            return View(affiche);
        }

        public ActionResult GetLutteurPourCombat(int combatId)
        {
            var combat = db.Combats.Where(c => c.CombatID == combatId).SingleOrDefault();
            var lutts = db.Lutteurs.Where(l => l.LutteurPoids >= combat.Categorie.Categorie_Min &&
             l.LutteurPoids <= combat.Categorie.Categorie_Max).ToList();
            
            return Json(lutts, JsonRequestBehavior.AllowGet);
        }


        // GET: Affiche/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Affiche affiche = db.Affiches.Find(id);
            if (affiche == null)
            {
                return HttpNotFound();
            }
            ViewBag.AfficheID = new SelectList(db.AvisAffiches, "AvisAfficheID", "Auteur", affiche.AfficheID);
            ViewBag.Lutteur_A = new SelectList(db.Lutteurs, "LutteurID", "LutteurName", affiche.Lutteur_A);
            ViewBag.Lutteru_B = new SelectList(db.Lutteurs, "LutteurID", "LutteurName", affiche.Lutteru_B);
            ViewBag.CombatID = new SelectList(db.Combats, "CombatID", "Combat_Description", affiche.CombatID);
            return View(affiche);
        }

        // POST: Affiche/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AfficheID,AfficheNom,CombatID,Lutteur_A,Lutteru_B,DateCombat,Vaincqueur,imageUrl")] Affiche affiche, HttpPostedFileBase ImageUpload)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    if (ImageUpload != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(ImageUpload.FileName);
                        string extension = Path.GetExtension(ImageUpload.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
                        affiche.imageUrl = fileName;
                        ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Images/Image-Affiche"), fileName));
                    }
                    db.Entry(affiche).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    return RedirectToAction("Index", "Error");
                }
            }


            ViewBag.AfficheID = new SelectList(db.AvisAffiches, "AvisAfficheID", "Auteur", affiche.AfficheID);
            ViewBag.Lutteur_A = new SelectList(db.Lutteurs, "LutteurID", "LutteurName", affiche.Lutteur_A);
            ViewBag.Lutteru_B = new SelectList(db.Lutteurs, "LutteurID", "LutteurName", affiche.Lutteru_B);
            ViewBag.CombatID = new SelectList(db.Combats, "CombatID", "Combat_Description", affiche.CombatID);

            return View(affiche);
        }

        // GET: Affiche/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Affiche affiche = db.Affiches.Find(id);
            if (affiche == null)
            {
                return HttpNotFound();
            }
            return View(affiche);
        }

        // POST: Affiche/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Affiche affiche = db.Affiches.Find(id);
            List<AvisAffiche> laa = db.AvisAffiches.Where(v => v.AfficheID == id).ToList();
            foreach (var item in laa)
            {
                db.AvisAffiches.Remove(item);
            }
          
            db.Affiches.Remove(affiche);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lamb_Ji_UI/Views/Affiche/Create.cshtml
@model Lamb_Ji_DAL.Affiche

@{
    /**/

    ViewBag.Title = "Create";
}
<style>
    #myCarousel {
        display: none;
    }

</style>
<h2>Creer une Nouvelle Affiche</h2>

@if (ViewBag.result != "")
{
    <div class="alert alert-danger">
        
        @ViewBag.result
    </div>

}

@using (Html.BeginForm("Create", "Affiche", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return jQueryAjaxPost2(this);" }))
{

    @Html.AntiForgeryToken()

    <div class="row">
        <div class="form-horizontal">

            <hr />
            <div class="col-md-6">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.AfficheNom, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AfficheNom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AfficheNom, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CombatID, "CombatID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CombatID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CombatID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Lutteur_A, "Lutteur_A", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Lutteur_A", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Lutteur_A, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Lutteru_B, "Lutteru_B", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Lutteru_B", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Lutteru_B, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateCombat, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateCombat, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateCombat, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.imageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img src="~/Images/Image-Lutteur/default.png" style="margin:10px" height="250" width="200" id="imagePreview" />
                        <input id="ImageUpload" name="ImageUpload" class="form-control" type="file" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))" />
                    </div>
                </div>
            </div>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à la Liste", "Index", null, new { @class = "btn btn-default btn-lg" })
</div>


@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        function ShowImagePreview(imageUploader, previewImage) {
            if (imageUploader.files && imageUploader.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(previewImage).attr('src', e.target.result);
                }
                reader.readAsDataURL(imageUploader.files[0]);
            }
        }


        function jQueryAjaxPost(form) {
            $.validator.unobtrusive.parse($('#SubmitForm'));
            if ($('#SubmitForm').valid()) {

                var ajaxConfig = {
                    type: 'POST',
                    url: form.action,
                    data: new FormData(form),
                    success: function () {
                        //$('#chargement').show();

                        //$('#chargement').hide();

                        toastr.info("Lutteur ajouté avec succés!!!....");

                    }
                }
                if ($(form).attr('enctype') == "multipart/form-data") {
                    ajaxConfig["contentType"] = false;
                    ajaxConfig["processData"] = false;
                }
                $.ajax(ajaxConfig);

            }
            return false;
        }


    </script>

}

Lamb_Ji_UI/Views/Affiche/Delete.cshtml
@model Lamb_Ji_DAL.Affiche

@{
    ViewBag.Title = "Delete";
}
<style>
    #myCarousel {
        display: none;
    }
</style>


<h3>Etes vous sur de vouloir supprimer cette Affiche?</h3>
<div>
    <h4>@Model.AfficheNom</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AfficheNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AfficheNom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCombat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCombat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vaincqueur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vaincqueur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imageUrl)
        </dd>      

        <dt>
            @Html.DisplayNameFor(model => model.Lutteur.LutteurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lutteur.LutteurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lutteur1.LutteurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lutteur1.LutteurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Combat.Combat_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Combat.Combat_Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-danger" /> |
            @Html.ActionLink("Retourner à la Liste", "Index", null, new { @class = "btn btn-default btn-lg" })
        </div>
    }
</div>

Lamb_Ji_UI/Views/Affiche/Edit.cshtml
@model Lamb_Ji_DAL.Affiche

@{
    ViewBag.Title = "Edit";
}
<style>
    #myCarousel {
        display: none;
    }
</style>
<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Affiche", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="form-horizontal">
            <h4>Affiche</h4>
            <hr />
            <div class="col-md-6">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.AfficheID)

                <div class="form-group">
                    @Html.LabelFor(model => model.AfficheNom, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AfficheNom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AfficheNom, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CombatID, "CombatID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CombatID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CombatID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Lutteur_A, "Lutteur_A", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Lutteur_A", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Lutteur_A, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Lutteru_B, "Lutteru_B", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Lutteru_B", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Lutteru_B, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateCombat, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateCombat, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateCombat, "", new { @class = "text-danger" })
                    </div>
                </div>
                @if (Model.DateCombat < DateTime.Now)
                 {
                <div class="form-group">
                    @Html.LabelFor(model => model.Vaincqueur, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Vaincqueur, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Vaincqueur, "", new { @class = "text-danger" })
                    </div>
                </div>
                }




                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                @if (Model.imageUrl != null)
              {
                    <div class="form-group">

                        @Html.LabelFor(model => model.imageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <img src="~/Images/Image-Affiche/@Url.Content(Model.imageUrl)" style="margin:10px" height="250" width="200" id="imagePreview" />
                            <input id="ImageUpload" name="ImageUpload" class="form-control" type="file" 
                                   onchange="ShowImagePreview(this,document.getElementById('imagePreview'))" />
                        </div>
                    </div>
              }

                else 
                {
                <div class="form-group">

                    @Html.LabelFor(model => model.imageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img src="~/Images/Image-Lutteur/default.png" style="margin:10px" height="250" width="200" id="imagePreview" />
                        <input id="ImageUpload" name="ImageUpload" class="form-control" type="file" onchange="ShowImagePreview(this,document.getElementById('imagePreview'))" />
                    </div>
                </div>
                }

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à la Liste", "Index", null, new { @class = "btn btn-default btn-lg" })
</div>



@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>



        function ShowImagePreview(imageUploader, previewImage) {
            if (imageUploader.files && imageUploader.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(previewImage).attr('src', e.target.result);
                }
                reader.readAsDataURL(imageUploader.files[0]);
            }
        }

    </script>

}

Lamb_Ji_UI/Views/Affiche/Index.cshtml
@model IEnumerable<Lamb_Ji_DAL.Affiche>

@{
    ViewBag.Title = "Liste des Affiches";
}
<style>
    #myCarousel {
        display: none;
    }
</style>
<h2>Liste des Affiches</h2>

<p>
    @Html.ActionLink("Nouvelle Affiche", "Create", null, new { @class = "btn btn-primary btn-lg" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AfficheNom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Combat.Combat_Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lutteur.LutteurName)
        </th>
        <th>VS</th>
        <th>
            @Html.DisplayNameFor(model => model.Lutteur1.LutteurName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCombat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vaincqueur)
        </th>




        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AfficheNom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Combat.Combat_Description).ToString().Substring(0, 10)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lutteur.LutteurName)
        </td>
        <td>---</td>
        <td>
            @Html.DisplayFor(modelItem => item.Lutteur1.LutteurName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCombat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vaincqueur)
        </td>




        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.AfficheID }, new { @class = "btn btn-primary" }) |
            @*@Html.ActionLink("Details", "Details", new { id = item.AfficheID }, new { @class = "btn btn-default" }) |*@
            @Html.ActionLink("Supp", "Delete", new { id = item.AfficheID }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>