Lamb_Ji_UI/Controllers/AfficheUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lamb_Ji_DAL;
using Lamb_Ji_ViewModel;

namespace Lamb_Ji_UI.Controllers
{
    public class AfficheUserController : Controller
    {
        private CNGLUTTEDBEntities db = new CNGLUTTEDBEntities();

        // GET: AfficheUser
        public ActionResult Index()
        {
            try
            {
                var affiches = db.Affiches
             .Include(a => a.Lutteur)
             .Include(a => a.Lutteur1)
             .Include(a => a.Combat)
             .Include(a => a.AvisAffiches).Where(x => x.DateCombat > DateTime.Now).OrderBy(c => c.DateCombat);


                foreach (var aff in affiches)
                {
                    List<AvisAffiche> listAvis = db.AvisAffiches.Where(c => c.AfficheID == aff.AfficheID).ToList();
                    if (aff.Combat.Combat_Description.Length > 300)
                    {
                        aff.Combat.Combat_Description = aff.Combat.Combat_Description.Substring(0, 150)+"......";
                    }
                    
                    aff.AvisAffiches = listAvis;
                    if (aff.AvisAffiches.Count == 0)
                    {

                        aff.Note = 0;
                    }

                    else
                        aff.Note = Math.Round(aff.AvisAffiches.Average(a => a.note), 2);
                }
                return View(affiches.ToList());
            }
            catch (Exception)
            {

                throw;
            }
         

            
        }

        // GET: AfficheUser/Details/5
        public ActionResult DetailsAfficheAvecAvis(int id)
        {
          
            try
            {
                Affiche affiche = db.Affiches
              .Include(a => a.Combat)
              .Include(a => a.Lutteur)
              .Include(a => a.Lutteur1)
              .Where(s => s.AfficheID == id).FirstOrDefault();
                List<AvisAffiche> listAvis = db.AvisAffiches.Where(c => c.AfficheID == id).ToList();
                if (affiche == null)
                {
                    return RedirectToAction("Index");
                }

                AfficheAvecAvis vm = new AfficheAvecAvis();
                vm.AfficheID = affiche.AfficheID;
                vm.AfficheNom = affiche.AfficheNom;
                vm.Combat = affiche.Combat;
                vm.Lutteur = affiche.Lutteur;
                vm.Lutteur1 = affiche.Lutteur1;
                vm.DateCombat = affiche.DateCombat;
                vm.Vaincqueur = affiche.Vaincqueur;
                vm.imageUrl = affiche.imageUrl;
                if (listAvis.Count != 0)
                {
                    vm.Avis = listAvis.OrderByDescending(o => o.DateAvis).ToList();
                }

                return View(vm);
            }
            catch (Exception)
            {

                return RedirectToAction("Index", "Error");
            }

          
           

           


        }

      
    }
}

Lamb_Ji_UI/Controllers/AvisController.cs
using Lamb_Ji_DAL;
using Lamb_Ji_ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lamb_Ji_UI.Controllers
{
    public class AvisController : Controller
    {
        // GET: Avis
        [Authorize]
        public ActionResult LaisserUnAvis(int afficheID)
        {

            LaisserUnAvisViewModel vm = new LaisserUnAvisViewModel(); 
             
            using (var context = new CNGLUTTEDBEntities())
            {
                Affiche aff = context.Affiches.Where(a => a.AfficheID == afficheID).SingleOrDefault();
                if (aff == null)               
                    return RedirectToAction("Index", "AfficheUser");
                vm.AfficheID = aff.AfficheID;
                vm.NomAffiche = aff.AfficheNom;
            }

                return View(vm);
        }
        [HttpPost]
        [Authorize]
        public ActionResult SaveComment(string commentaire, string note, int afficheID)
        {
            AvisAffiche nouvelAvis = new AvisAffiche();
            
            nouvelAvis.DateAvis = DateTime.Now;
            nouvelAvis.Message = commentaire;
            nouvelAvis.Auteur = User.Identity.Name;
            double dnote = 0;
            if (!double.TryParse(note,NumberStyles.Any,CultureInfo.InvariantCulture, out dnote))
            {
                throw new Exception("Impossible de parser la note"+note);
            }
            nouvelAvis.note = dnote;
            using (var context = new CNGLUTTEDBEntities())
            {
                Affiche aff = context.Affiches.Where(a => a.AfficheID == afficheID).SingleOrDefault();
                if (aff == null)
                {
                    return RedirectToAction("Index", "AfficheUser");
                }
                //var p = context.AvisAffiches.ToList();
                //var maxId = p.Max(x => x.AvisAfficheID);
                //nouvelAvis.AvisAfficheID = maxId + 1;
                nouvelAvis.AfficheID = aff.AfficheID;
                context.AvisAffiches.Add(nouvelAvis);
                context.SaveChanges();
            }
            return RedirectToAction("DetailsAfficheAvecAvis", "AfficheUser", new {id = afficheID });
        }
    }
}

Lamb_Ji_UI/Views/AfficheUser/Details.cshtml
@model Lamb_Ji_DAL.Affiche

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Affiche</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AfficheNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AfficheNom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCombat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCombat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vaincqueur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vaincqueur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvisAffiche.Auteur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvisAffiche.Auteur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lutteur.LutteurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lutteur.LutteurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lutteur1.LutteurName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lutteur1.LutteurName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Combat.Combat_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Combat.Combat_Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AfficheID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lamb_Ji_UI/Views/AfficheUser/DetailsAfficheAvecAvis.cshtml
@model Lamb_Ji_ViewModel.AfficheAvecAvis
@{
    ViewBag.Title = "DetailsAfficheAvecAvis";
}
<style>
    #myCarousel {
        display: none;
    }

    h4 {
        color: #241f9b;
    }
</style>
<h2 class="text-center">@Model.AfficheNom</h2>
<br />
<div class='section content'>
    <div class='illustration'>
        <img src="~/Images/Image-Affiche/@Model.imageUrl" style="max-width: 1200px; height:500px" />
    </div>
</div>

<br />
<div>

    <h4> @Model.Lutteur.LutteurName</h4>

    <span>VS</span>
    <h4> @Model.Lutteur1.LutteurName</h4>
</div>
<p>
    @Model.Combat.Combat_Description
</p>
@if (Model.Avis.Count > 0)
{
    foreach (var avis in Model.Avis)
    {
        <div>
            <br />
            <div>@avis.Auteur</div>
            <div>@avis.Message</div>
            <div>@avis.DateAvis.ToShortDateString()</div>

        </div>
    }

}
<div>
    <a href="@Url.Action("LaisserUnAvis", "Avis", new { afficheID  = Model.AfficheID })">Laisser un commentaire</a>
</div>



<br /><br /><br />
@Html.ActionLink("Retourner à la Liste des Combats", "Index", null, new { @class = "btn btn-block btn-default" })

Lamb_Ji_UI/Views/AfficheUser/Index.cshtml
@model IEnumerable<Lamb_Ji_DAL.Affiche>

@{
    ViewBag.Title = "Calendrier des combats";
}

<h2 class="text-center">Liste des Combat à venir</h2>

<style>

    .circle-img {
        width: 250px;
        height: 250px;
        overflow: hidden;
    }

        .circle-img img {
            height: 100%;
            transform: translateX(-50%);
            margin-left: 50%;
        }

    hr {
        display: block;
        height: 2px;
        border: 0;
        border-top: 1px solid #0094ff;
        margin: 1em 0;
        padding: 0;
    }
    .blue {
        color: blue;
    }
</style>


@foreach (var item in Model)
{
  
    <hr />
    <div class="row">

        <div>
            <a href="@Url.Action("DetailsAfficheAvecAvis", "AfficheUser", new { id = item.AfficheID })"> <h2> @Html.DisplayFor(modelItem => item.AfficheNom)</h2></a>
        </div>
        <div class="col-md-4 how-img circle-img img-circle">
            <img class="img-responsive img-circle img-fluid" src="~/Images/Image-Affiche/@item.imageUrl" />

        </div>
        <div class="col-md-8">
            <div>
                @Html.DisplayFor(modelItem => item.Combat.Combat_Description)<br /><br />
            </div>
            <div>
                <h4 style="color:navy"> @Html.DisplayFor(modelItem => item.Lutteur.LutteurName)</h4>
                <span>--- VS ---</span>
                <h4 style="color:navy"> @Html.DisplayFor(modelItem => item.Lutteur1.LutteurName)</h4>
            </div>
            <p>
                le combat aura lieu le :
                @Html.DisplayFor(modelItem => item.DateCombat) au stade
                @Html.DisplayFor(modelItem => item.Combat.Stade.StadeName)
            </p>
            <br />
            <div>
                <article class="info-block">
                    <p>
                        <span class="glyphicon glyphicon-star blue"></span>
                        @if (item.Note > 1)
                {
                    <span class="glyphicon glyphicon-star blue"></span>
        }
                        @if (item.Note > 2)
                {
                    <span class="glyphicon glyphicon-star blue"></span>
        }
                        @if (item.Note > 3)
                {
                    <span class="glyphicon glyphicon-star blue"></span>
        }
                        @if (item.Note > 4)
                {
                    <span class="glyphicon glyphicon-star blue"></span>
        }

                        @item.Note / 5
                    </p>
                </article>

            </div>
        </div>
    </div>

}